
@startuml UmbrellaActivities
|New SW Project|

start

#GreenYellow:Start Project;

|#LavenderBlush|Umbrella Activities|
repeat

split
  :software project tracking;
split again
  :risk management;
split again
  :software quality assurance;
split again
  :measurement;
split again
  :software configuration management;
split again
  :reusability management;
split again
  :work product preparation and production;
end split;
backward :Next Sprint;
repeatwhile (Last Sprint) is (NO) not (YES)
|New SW Project|

#GreenYellow:release;

@enduml

