
@startuml UmbrellaActivities
|New SW Project|

start

#GreenYellow:Start Project;

|#LavenderBlush|Umbrella Activities|
repeat

split
  :**__software project tracking__**

  gauge current progress
  against project plan
  and make any adjustments
  ;
split again
  :**__risk management__**

  Asses any risks or potential risks
  that may affect the outcome of the project
  ;
split again
  :**software quality assurance**
  
  Perform continuous quality assurance 
  activites
  ;
split again
  :**__measurement__**
  
  Assist the team in measurments that
  ensure project is meeting customer needs
  ;
split again
  :**__software configuration management__**

  Manage the effects of various changes
  in the project lifecycle;
split again
  :**__reusability management__**

  Identify criteria for product reusability 
  and component reusability
  ;
split again
  :**__work product preparation and production__**

  Activities required to product work related collateral 
  such as models or documents
  ;
end split;
backward :Continue;
repeatwhile (Project Complete) is (NO) not (YES)
|New SW Project|

#GreenYellow:release;

@enduml

